mysql:
  host: 127.0.0.1
  port: 3306
  db: blog_db
  username: root
  password: 401026211
  log_level: dev
  config: charset=utf8&parseTime=True
  maxIdleConns: 10
  maxOpenConns: 25
logger:
  level: info
  prefix: '[blog]'
  director: log
  show-line: true
  log-in-console: true
server:
  host: "0.0.0.0"
  port: 8080
  env: release
  jwtKey: dad131d1
cloud:
  accessKey: ijBXMvzdR8-IyCdNEwXih09FReYNVDFhIBjCLCDL
  secretKey: T0g3r1FFl5_SOgfPnZzpvraqOjvyb4ZiyjZkpOJz
  bucket: ginblogz
  host: http://s5x5qudhm.hd-bkt.clouddn.com/

